name: ✨ Feature Request
description: 建议一个新功能或改进
title: "[FEATURE] "
labels: ["enhancement", "needs-triage"]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        感谢您的功能建议！请详细描述您的想法，这将帮助我们更好地理解和实现。

  - type: input
    id: feature-type
    attributes:
      label: 功能类型
      description: 这是什么类型的功能请求？
      placeholder: "例如: 新Agent角色, 新Command, 工具集成, UI改进等"
    validations:
      required: true

  - type: textarea
    id: problem
    attributes:
      label: 问题描述
      description: 您希望解决什么问题？请描述您的使用场景。
      placeholder: |
        当我在...时，我遇到了...
        这影响了我的工作效率，因为...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: 期望的解决方案
      description: 您希望我们实现什么功能？请尽可能详细地描述。
      placeholder: |
        我希望能够...
        这个功能应该...
        用户界面可以...
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: 替代方案
      description: 您是否考虑过其他解决方案？
      placeholder: 描述您考虑过的其他方法...
    validations:
      required: false

  - type: textarea
    id: examples
    attributes:
      label: 使用示例
      description: 如果可能，请提供一些使用示例或代码片段
      render: bash
      placeholder: |
        # 期望的命令用法
        /new-command --option value
        
        # 期望的配置
        new_agent:
          type: specialist
          tools: [tool1, tool2]
    validations:
      required: false

  - type: checkboxes
    id: scope
    attributes:
      label: 功能范围
      description: 这个功能主要涉及哪些方面？
      options:
        - label: Agent角色扩展
        - label: Command功能增强
        - label: Hook自动化
        - label: MCP服务器集成
        - label: Git Worktree工作流
        - label: 用户界面改进
        - label: 性能优化
        - label: 文档和教程
        - label: 其他

  - type: dropdown
    id: priority
    attributes:
      label: 优先级
      description: 您认为这个功能有多重要？
      options:
        - 低 - 有了更好，没有也无妨
        - 中 - 会显著改善体验
        - 高 - 解决重要痛点
        - 紧急 - 阻塞了关键工作流
    validations:
      required: true

  - type: textarea
    id: benefits
    attributes:
      label: 预期收益
      description: 实现这个功能后会带来什么好处？
      placeholder: |
        - 提升开发效率 X%
        - 减少手动操作
        - 改善用户体验
        - 支持新的使用场景
    validations:
      required: false

  - type: checkboxes
    id: contribution
    attributes:
      label: 贡献意愿
      description: 您是否愿意参与这个功能的开发？
      options:
        - label: 我愿意帮助设计这个功能
        - label: 我愿意参与代码实现
        - label: 我愿意帮助测试
        - label: 我愿意帮助编写文档

  - type: checkboxes
    id: checklist
    attributes:
      label: 检查清单
      description: 在提交前请确认以下事项
      options:
        - label: 我已经搜索了现有的issues和discussions，确认这不是重复建议
          required: true
        - label: 我已经阅读了项目文档和roadmap
          required: true
        - label: 这个功能符合项目的整体目标和愿景
          required: true